!!python/object/new:lightning.pytorch.utilities.parsing.AttributeDict
dictitems:
  batch_size: 32
  dataset_length: 10281
  dropout_rate: 0.1
  embed_size: 768
  forward_expansion: 4
  heads: 12
  max_epochs: 10
  num_layers: 12
  sequence_length: 1024
  vocab_size: 50233
